import { StyleSheet } from 'react-native';

export const colors = {
  primary: '#3B82F6',
  secondary: '#10B981',
  purple: '#8B5CF6',
  background: '#F5F7FA',
  cardBg: '#F9FAFB',
  border: '#E5E7EB',
  text: {
    primary: '#1F2937',
    secondary: '#6B7280',
    placeholder: '#999',
    red: '#ef4444',
    yellow: '#F59E0B',
  },
  disabled: '#D1D5DB',
  success: '#E1EDE0',
  info: '#9ca3af',
  infoBorder: '#BFDBFE',
  redBackground: '#fee2e2',
  yellowBackground: '#FFF3CD',
  purpleBackground: '#f3d9ff',
  white: '#FFFFFF',
};

export const sharedStyles = StyleSheet.create({
  card: {
    backgroundColor: colors.background,
    borderColor: colors.border,
    borderRadius: 16,
    shadowColor: colors.border,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 3,
    display: 'flex',
    justifyContent: 'center',
  },
  input: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.cardBg,
    borderWidth: 2,
    borderColor: colors.border,
    borderRadius: 12,
    padding: 10,
    fontSize: 16,
    color: colors.text.primary,
  },
  inputText: {
    color: colors.text.primary,
    fontSize: 16,
    fontWeight: '500',
  },
  inputSelected: {
    borderColor: colors.secondary,
    backgroundColor: colors.secondary + '10',
  },
  inputSelectedText: {
    color: colors.secondary,
    fontWeight: '600',
  },
  button: {
    borderRadius: 12,
    alignItems: 'center',
    marginTop: 8,
    backgroundColor: colors.cardBg + '30',
    borderColor: colors.text.secondary,
  },
  buttonDisabled: {
    backgroundColor: colors.disabled,
  },
  buttonText: {
    color: colors.text.secondary,
    fontSize: 15,
    fontWeight: '600',
  },
  primaryButton: {
    backgroundColor: colors.primary,
    paddingVertical: 15,
    paddingHorizontal: 15,
    borderRadius: 12,
    alignItems: 'center',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 5,
  },
  primaryButtonText: {
    color: colors.background,
    fontSize: 18,
    fontWeight: '600',
  },
  secondaryButton: {
    paddingVertical: 15,
    paddingHorizontal: 15,
    borderRadius: 12,
    borderWidth: 2,
    alignItems: 'center',
    backgroundColor: colors.cardBg,
    color: colors.primary,
    borderColor: colors.primary,
    elevation: 5,
  },
  secondaryButtonText: {
    color: colors.primary,
    fontSize: 18,
    fontWeight: '600',
  },
  backButton: {
    marginBottom: 12,
    marginTop: 12,
    padding: 20,
  },
  backButtonText_patient: {
    fontSize: 16,
    color: colors.primary,
    fontWeight: '500',
  },
  backButtonText_caregiver: {
    fontSize: 16,
    color: colors.secondary,
    fontWeight: '500',
  },
  redButton: {
    backgroundColor: colors.redBackground,
    marginHorizontal: 16,
    marginTop: 8,
    borderRadius: 12,
  },
  redText: {
    display: 'flex',
    justifyContent: 'center',
    color: colors.text.red,
  },
  closeButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: colors.redBackground,
    justifyContent: 'center',
    alignItems: 'center',
  },
  closeButtonText: {
    fontSize: 20,
    color: colors.text.red,
  },
  cancelButton: {
    backgroundColor: colors.cardBg,
    borderColor: colors.border,
    borderWidth: 2,
  },
  cancelButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: colors.text.secondary,
  },
  confirmButton: {
    backgroundColor: colors.text.red,
  },
  confirmButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: colors.cardBg,
  },
  checkboxCircle: {
    width: 20,
    height: 20,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: colors.border,
    marginRight: 12,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: colors.background,
  },
  checkboxSelected: {
    borderColor: colors.secondary,
  },
  checkboxDot: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: colors.secondary,
  },
  helperBox: {
    backgroundColor: colors.primary + '10',
    padding: 16,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.primary + '30',
  },
  helperText: {
    fontSize: 14,
    color: colors.text.secondary,
    fontWeight: '500',
    fontStyle: 'italic',
  },
  menuArrow: {
    fontSize: 24,
    color: colors.info,
    fontWeight: '500',
  },
  iconCircle: {
    width: 56,
    height: 56,
    borderRadius: 28,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  iconText: {
    fontSize: 28,
  },
});